CyberElites-NSAKCET/Resources

QRCode_Generator/qrcode_generator.py
This pull request enhances the QRCode Generator by adding functionality to include a title above the generated QR codes. This feature allows us to customize the QR codes with a descriptive title, improving readability and usability.
- **Enhanced**: `qrcode_generator.py` script to support the addition of titles to QR codes.
- **Added**: Functionality to include a title above QR codes.
- **Updated**: Script to ensure the title is customizable and properly formatted.
The enhancement aims to provide users with the ability to add a title to their QR codes, making the generated QR codes more informative and useful for various applications.
- The QRCode Generator script has been tested locally to ensure that titles are added correctly above QR codes.
- Verified that the title customization …
=> Enhance QRCode Generator to include title for QR codes.

QRCode_Generator/qrcode_generator.py
This pull request adds comprehensive documentation strings (docstrings) to all functions in the QRCode Generator script. The addition of these docstrings improves the readability and maintainability of the code by providing detailed descriptions of the purpose, parameters, and return values of each function.
- **Added**: Docstrings to each function in `qrcode_generator.py`.
- **Provided**: Detailed descriptions of the purpose, parameters, and return values for each function.
- **Improved**: Code readability and maintainability through thorough documentation.
The purpose of this enhancement is to make the QRCode Generator script more understandable and easier to maintain by adding clear and informative documentation strings to all functions. This helps other developers quickly understand …
=> Add Documentation Strings to All Functions in QRCode Generator Script

QRCode_Generator/qrcode_generator.py, requirements.txt
This pull request introduces new functions for file retrieval and font selection, adds a `requirements.txt` file for managing dependencies, and includes minor improvements to the existing code.
- **Added**: `get_files(directory, extension)` function to retrieve files with a specific extension from a given directory.
- **Added**: `select_font()` function to prompt the user to select a TrueType font from the available fonts in the fonts directory.
- **Included**: `requirements.txt` file listing the necessary dependencies for the project.
- **Improved**: Minor code enhancements for better performance and readability.
The addition of these functions and the `requirements.txt` file aims to enhance the functionality and manageability of the QRCode Generator script. The `get_files` function …
=> Add File Retrieval and Font Selection Functions, requirements.txt, and Minor Code Improvements

QRCode_Generator/qrcode_generator.py
This pull request enhance font handling in `select_font` function and minimize code redundancy in defining directory paths.
- **Improved**: Minor code enhancements for font handling in `select_font` function.
- **Minimized**: Minimized code redundancy in defining directory paths.
The enhancement to handle fonts when there is no font file specified in "Fonts" directory helps in minimizing any runtime errors and better user experience. Minimizing the redundancy in code for directory paths provides easy understanding of the code and improves readability.
- Tested the `select_font` function to confirm that it acknowledges the user when there is no font specified.
- Tested the `get_files` function to ensure it correctly retrieves files with the specified extension.
- Reviewed the minor code …
=> Enhance font handling and Minimize Code redundancy

Certificate_Generator/certificate_generator.py
This pull request updates the certificate generation script to support landscape orientation and implement import error handling.
- **Modified**: The `create_certificate` function to use landscape A4 page size.
- **Adjusted**: Text position to better fit the landscape orientation.
- **Implemented**: Error handling for missing modules, providing clear instructions for installation.
The purpose of this pull request is to enhance the flexibility and robustness of the certificate generation tool. By switching to a landscape orientation and improving text alignment, the generated certificates will look more professional. Additionally, the implemented error handling ensures that users receive clear guidance on how to resolve missing dependencies.
- Tested the `create_certificate` function with …
=> Update certificate generation script for landscape orientation and implement error handling

Certificate_Generator/certificate_generator.py
This pull request enhances the certificate generation script with additional features, including font selection, text file reading, and improved error handling. The updates ensure a more robust and user-friendly experience for generating personalized certificates.
- **Added**: Functionality to select a font from a directory of TrueType fonts.
- **Implemented**: Reading names from a text file for batch certificate generation.
- **Enhanced**: Error handling for missing files and invalid user inputs.
The purpose of this pull request is to improve the flexibility and usability of the certificate generation tool. By allowing font selection and reading names from a text file, users can easily customize and generate multiple certificates in one go. The improved error handling ensures smoother …
=> Enhance certificate script with font selection, text file reading, and improved error handling

.gitignore, Certificate_Generator/certificate_generator.py
This pull request enhances the certificate generation script with improved functionality of code. Adds comprehensive documentation strings (docstrings) to all functions. Updates to `.gitignore` file helps maintain a clean and organized codebase by excluding unnecessary files and directories from version control.
- **Added**: Docstrings to each function in `certificate_generator.py`.
- **Provided**: Detailed descriptions of the purpose, parameters, and return values for each function.
- **Improved**: Code readability and functionality to minimize redundancy.
- **Updated**: `.gitignore` file to maintain clean codebase.
The purpose of this pull request is to enhance the certificate generation script with improved functionality of code. It adds comprehensive documentation strings (docstrings) …
=> Improve certificate generation script functionality and readability, Add doc strings, Update .gitignore

Email_Sender/send_email.py
This pull request introduces a new script, `send_email.py`, designed for sending emails via Gmail's SMTP server. The script includes features such as support for multiple recipients, optional attachments, and secure authentication using Gmail App Passwords.
- **Added**: `send_email.py` script for automated email sending with:
- Multiple recipients support
- Optional file attachments (supports any file type)
- Secure authentication via TLS and Gmail App Passwords
- Error logging for troubleshooting
The addition of this script aims to provide an easy-to-use tool for sending emails with attachments from a Gmail account to improve workflow efficiency.
- Tested email sending with multiple recipients and various attachments (PDF, TXT).
- Verified Gmail SMTP authentication with App Password.
- …
=> Added 'send_email.py' script for sending emails with attachments via Gmail SMTP

App_Scripts/README.md, App_Scripts/sheet_appscript.js
This pull request introduces a comprehensive setup for automating email responses to Google Form submissions. It includes the core script file and a detailed README for implementation and usage instructions.
- **Script Implementation**:
- Added `appscript.js` containing the logic for sending personalized HTML emails, email validation, and error logging.
- Includes features for setting up triggers to handle form submissions automatically.
- **Documentation**:
- Added a `README.md` file with clear instructions for setting up and using the script.
- Documentation highlights features like error logging, email validation, and Gmail limits.
These additions simplify the process of automating Google Form submissions, providing users with an easy-to-follow guide and a ready-to-use script. The …
=> Added App_Scripts folder with appscript.js and README.md for Google Form automation.

App_Scripts/README.md, Certificate_Generator/README.md, QRCode_Generator/README.md
This pull request adds detailed README files for the Certificates Generator and QR Code Generator scripts. These README files include comprehensive instructions on how to set up and run the scripts, making it easier for users to understand and use these tools effectively.  
- **Certificates Generator README**:  
- Provided step-by-step instructions for setting up and running the Certificates Generator script.  
- Included details about required dependencies, input file formats, and customization options.  
- **QR Code Generator README**:  
- Added detailed steps for generating both Dot and Standard QR Codes.  
- Explained input requirements, available styling options, and example outputs.  
The addition of README files improves the accessibility and usability of the Certificates Generator …
=> Added Readme for Certificate Generator and QRCode Generator

Certificate_Generator/README.md, QRCode_Generator/README.md
This pull request addresses and corrects errors in the README files for the Certificates Generator and QR Code Generator scripts, ensuring accurate and clear instructions for users.  
- Corrected typos and clarified ambiguous instructions in the README files.  
- Updated formatting for better readability.  
These updates improve the quality and clarity of the documentation, making it easier for users to set up and use the scripts effectively.  
Please review the changes and provide feedback for merging.
=> Fixed Errors in README Files for Certificates and QR Code Generators

QRCode_Generator/qrcode_generator.py
Thanks to @Raqeeb27  , replaced all exit() calls with sys.exit()
=> Added proper exit handling using sys.exit() method

CONTRIBUTING.md
Added guidelines for using labels in pull requests.
=> feat(contributions): Add label guidelines to CONTRIBUTING.md

Certificate_Email_Automation/README.md
Updated README to clarify features, configuration, and usage instructions for the Certificate Email Automation script.
=> docs(cert-email): Enhance README with detailed features and setup instructions

App_Scripts/README.md
- Updated the README to include additional steps for configuring the email script, setting up triggers, and testing the automation.  
- Enhanced clarity with new images and instructions.
=> docs(appscript): Revise README for AppScript automation setup

extract_certify_and_email.py
Corrected the indentation for the try-except block in main, ensuring smooth execution of the external scripts from code.
Verified that the script executes successfully from a directory path containing spaces.
=> refactor(cert-email): Fix indentation for try-except block in main

QRCode_Generator/qrcode_generator.py
- Use absolute paths for the directories instead of relative paths
- Shorten the variable naming conventions
=> refactor(qr): Improve directory handling structure

Certificate_Generator/certificate_generator.py
- Use absolute paths for the directories instead of relative paths
- Shorten the variable naming conventions
=> refactor(cert-gen): Improve directory handling structure

Email_Sender/email_config.json, Email_Sender/email_html_body_template.html
- Add `email_config.json` file
- Add `email_html_body_template.html` file
=> feat(email): Initialize and add required files

Certificate_Email_Automation/cert-email_config.json, Certificate_Email_Automation/cert-email_html_body_template.html
- `cert-email_config.json` file
- `cert-email_html_body_template.html` file
=> feat(cert-email): Initialize and add required files

Certificate_Email_Automation/extract_certify_and_email.py
- Use absolute paths for the directories instead of relative paths
- Shorten the variable naming conventions
=> refactor(cert-email): Improve directory handling structure

Email_Sender/send_email.py
- Remove redundant try-except block
- Import and handle socket.error
=> chore,refactor(email): Handle socket.error & restructre send_email()
